# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/TEMP/Desktop/partc/partc.cache/wt [current_project]
set_property parent.project_path D:/Users/TEMP/Desktop/partc/partc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/Users/TEMP/Desktop/partc/partc.srcs/sources_1/new/pulse_controller.sv
  D:/Users/TEMP/Desktop/partc/partc.srcs/sources_1/new/display_controller.sv
  D:/Users/TEMP/Desktop/partc/partc.srcs/sources_1/new/timer.sv
  D:/Users/TEMP/Desktop/partc/partc.srcs/sources_1/new/datapath.sv
  D:/Users/TEMP/Desktop/partc/partc.srcs/sources_1/new/controller.sv
  D:/Users/TEMP/Desktop/partc/partc.srcs/sources_1/new/Integration.sv
  D:/Users/TEMP/Desktop/partc/partc.srcs/sources_1/new/_4x4_keypad_scanner.sv
}
read_xdc D:/Users/TEMP/Desktop/partc/partc.srcs/constrs_1/new/xdc.xdc
set_property used_in_implementation false [get_files D:/Users/TEMP/Desktop/partc/partc.srcs/constrs_1/new/xdc.xdc]

synth_design -top _4x4_keypad_scanner -part xc7a35tcpg236-1
write_checkpoint -noxdef _4x4_keypad_scanner.dcp
catch { report_utilization -file _4x4_keypad_scanner_utilization_synth.rpt -pb _4x4_keypad_scanner_utilization_synth.pb }
